create table if not exists users (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists roles (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists permissions (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists audit_log (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text, actor text, action text, resource_type text, resource_id text, trace_id text);
create table if not exists data_license_registry (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists data_snapshot_registry (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists dataset_snapshot_manifest (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text, snapshot_id text unique, data_version text, source text, license_id text, manifest_hash text, status text, as_of text);
create table if not exists schema_registry (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text, schema_name text, schema_version text, layer text, contract_path text);
create table if not exists factor_registry (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists feature_registry (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists model_registry (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists experiment_run (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists pipeline_task_run (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists spark_job_run (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text, run_id text unique, job_name text, input_snapshot_id text, output_snapshot_id text, config_hash text, status text);
create table if not exists flink_job_run (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text, run_id text unique, job_name text, input_topics text, output_topics text, checkpoint_path text, status text);
create table if not exists report_registry (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists rag_document (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists rag_chunk (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists rag_claim (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text, claim_id text unique, document_id text, citation_span text, evidence_direction text, evidence_strength text, as_of text);
create table if not exists graph_node (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists graph_edge (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists simulation_account (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists simulation_order (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists simulation_position (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists export_manifest (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text, export_id text unique, report_id text, license_gate_status text, file_hash text, status text);
create table if not exists backfill_request (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists adr_record (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text);
create table if not exists risk_register_item (id integer primary key autoincrement, created_at text not null default current_timestamp, updated_at text, risk_id text unique, title text, severity text, mitigation text, owner text, status text);
